fix: replace single-quotes with double quotes for Windows compatility
Ubuntu is indifferent whether we run `uv add 'pydantic-ai[option]' `or `"uv add 'pydantic-ai[option]"`, but Windows errors with this message:

```
error: Failed to parse: `'pydantic-ai[logfire]'`
  Caused by: Expected package name starting with an alphanumeric character, found `'`
'pydantic-ai[logfire]'
```

I'm on Windows 11 Version 24H2, x64 based-processor
Using uv 0.6.6 (c1a0bb85e 2025-03-12) and python 3.12.9