Add new _GeminiThoughtPart to adhere to Gemini response
The VertexAI docs mention that fields `thought` and `thoughSignature`
might be present in a part.  The `thought` field indicates "if the
part is thought from the model".  See
https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1/Content#Part

This is a simple fix to avoid validation errors because the current
schema refuses to accept responses that contain a 'thought part'
currently.

The failure would look like this:

```
File "/var/lang/lib/python3.12/site-packages/pydantic/type_adapter.py", line 468, in validate_json
  return self.validator.validate_json(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for _GeminiResponse
candidates.0.content.parts.0.text.text
Field required [type=missing, input_value={'thought': True, 'though...CPmF0DeNlHMlqQaW2asg9c'}, input_type=dict]
  For further information visit https://errors.pydantic.dev/2.11/v/missing
```